In [2]:
import pandas as pd
from pathlib import Path

In [12]:
currPath=Path.cwd()
input_file = currPath.parents[1]/"Datasets/DESeq2Input/lungNormalCounts.csv"
output_file = currPath.parents[1]/"Datasets/DESeq2Input/lungNormalCounts.tabular"

In [13]:
# Read CSV file
df = pd.read_csv(input_file)

# Save as a tab-separated file
df.to_csv(output_file, sep="\t", index=False)

print("Conversion complete: CSV to tabular format.")

Conversion complete: CSV to tabular format.

In [84]:
# normal_path = currPath.parents[1]/"Datasets/DESeq2Input/breastNormalCounts.csv"
# cancer_path = currPath.parents[1]/"Datasets/DESeq2Input/breastCancerCounts.csv"

In [98]:
normal_path = currPath.parents[1]/"Datasets/DESeq2Input/lungNormalCounts.csv"
cancer_path = currPath.parents[1]/"Datasets/DESeq2Input/lungCancerCounts.csv"

In [99]:
df_normal = pd.read_csv(normal_path)
df_cancer = pd.read_csv(cancer_path)

In [101]:
common_genes = df_normal.index.intersection(df_cancer.index)

# Filter both dataframes
df_normal_filtered = df_normal.loc[common_genes]
df_cancer_filtered = df_cancer.loc[common_genes]

In [107]:
df_cancer_filtered.index = df_cancer_filtered['gene_id']
df_normal_filtered.index = df_normal_filtered['gene_id']

In [108]:
df_cancer_filtered= df_cancer_filtered.drop('gene_id', axis = 1) # Remove the gene_id which is present as a separate column
df_normal_filtered= df_normal_filtered.drop('gene_id', axis = 1) # Remove the gene_id which is present as a separate column

In [59]:
# output_file_cancer = currPath.parents[1]/"Datasets/DESeq2Input/breastNormalCounts.tabular"
# output_file_normal = currPath.parents[1]/"Datasets/DESeq2Input/breastCancerCounts.tabular"

In [60]:
df_cancer_filtered

,2c3000b7-4db9-4f00-a82a-ca6802806631,519b92e0-0dbc-471c-988f-48ce9dc95be3,f2bf29d2-4c33-4810-90e8-88f37ea47bc8,59858555-bc6a-4286-8280-0f8341123cac,de6f1503-33d7-4f86-b835-bdffba7ea4e3,f0a63361-78bb-4a7f-9d78-31f7b2980ba2,121a48ed-798d-4102-bb8f-e736570e18d6,afedbcf7-d427-4371-9c2a-f349b03de522,82004d79-07d3-4a01-b266-4d36353ba561,4e98f490-cbdf-4864-8cc3-b5f9d3c95146,...,f7b5d569-1a46-4f23-bfca-a46daacda793,d889e5ea-58f5-4d2f-ad1e-6ab5d3217642,39b28d5e-fc51-4dfc-bcbe-0285c3bad830,08837ae7-6f4f-4aa1-8722-7c404b66ed75,4c941474-f3e0-4735-bad0-cff8894fb08d,5dee4a6f-9cf4-4360-a37b-e7b94aa70dac,86d52d54-1b0d-40b1-99ce-82b4e345acb8,451ecdf8-433f-4d38-8ab6-3cc8d428ed95,67347e29-6d43-4234-8b04-188be7e6440b,055f6138-ea7a-468d-90c2-87a473486867
gene_id,,,,,,,,,,,,,,,,,,,,,
ENSG00000000003.15,2304,1033,2967,9201,1162,745,2651,2683,3006,1073,...,2519,1588,2654,5552,3294,2287,457,4509,4324,8928
ENSG00000000005.6,7,4,17,9,90,0,162,96,37,0,...,3,49,53,12,251,47,0,68,0,7
ENSG00000000419.13,4979,2240,5568,4186,1703,1537,1096,2728,2278,2116,...,2398,4126,1492,4113,2117,2617,1949,2147,2559,1273
ENSG00000000457.14,1544,1702,3458,2054,1401,1798,1701,1765,2518,868,...,2931,1444,1965,1803,2937,3049,4082,2922,649,1356
ENSG00000000460.17,1723,587,2060,4333,876,497,532,624,644,392,...,1147,711,634,3206,837,1141,1351,366,638,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000279030.1,0,3,1,1,0,0,0,0,2,0,...,1,0,1,1,1,0,2,1,0,0
ENSG00000279031.1,10,18,28,25,14,4,8,46,15,74,...,26,21,13,36,6,58,20,10,8,45
ENSG00000279032.1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000279033.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000279034.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [88]:
# # Save as a tab-separated file
# df_cancer_filtered.to_csv(output_file_cancer,sep="\t",  index=True)
# df_normal_filtered.to_csv(output_file_normal, sep="\t", index=True)

In [109]:
df_cancer_filtered.to_csv(cancer_path, index=True)
df_normal_filtered.to_csv(normal_path, index=True)

In [62]:
df_test = pd.read_csv(output_file_cancer, sep="\t")

In [63]:
df_test

,gene_id,2c3000b7-4db9-4f00-a82a-ca6802806631,519b92e0-0dbc-471c-988f-48ce9dc95be3,f2bf29d2-4c33-4810-90e8-88f37ea47bc8,59858555-bc6a-4286-8280-0f8341123cac,de6f1503-33d7-4f86-b835-bdffba7ea4e3,f0a63361-78bb-4a7f-9d78-31f7b2980ba2,121a48ed-798d-4102-bb8f-e736570e18d6,afedbcf7-d427-4371-9c2a-f349b03de522,82004d79-07d3-4a01-b266-4d36353ba561,...,f7b5d569-1a46-4f23-bfca-a46daacda793,d889e5ea-58f5-4d2f-ad1e-6ab5d3217642,39b28d5e-fc51-4dfc-bcbe-0285c3bad830,08837ae7-6f4f-4aa1-8722-7c404b66ed75,4c941474-f3e0-4735-bad0-cff8894fb08d,5dee4a6f-9cf4-4360-a37b-e7b94aa70dac,86d52d54-1b0d-40b1-99ce-82b4e345acb8,451ecdf8-433f-4d38-8ab6-3cc8d428ed95,67347e29-6d43-4234-8b04-188be7e6440b,055f6138-ea7a-468d-90c2-87a473486867
0,ENSG00000000003.15,2304,1033,2967,9201,1162,745,2651,2683,3006,...,2519,1588,2654,5552,3294,2287,457,4509,4324,8928
1,ENSG00000000005.6,7,4,17,9,90,0,162,96,37,...,3,49,53,12,251,47,0,68,0,7
2,ENSG00000000419.13,4979,2240,5568,4186,1703,1537,1096,2728,2278,...,2398,4126,1492,4113,2117,2617,1949,2147,2559,1273
3,ENSG00000000457.14,1544,1702,3458,2054,1401,1798,1701,1765,2518,...,2931,1444,1965,1803,2937,3049,4082,2922,649,1356
4,ENSG00000000460.17,1723,587,2060,4333,876,497,532,624,644,...,1147,711,634,3206,837,1141,1351,366,638,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55171,ENSG00000279030.1,0,3,1,1,0,0,0,0,2,...,1,0,1,1,1,0,2,1,0,0
55172,ENSG00000279031.1,10,18,28,25,14,4,8,46,15,...,26,21,13,36,6,58,20,10,8,45
55173,ENSG00000279032.1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55174,ENSG00000279033.1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55175,ENSG00000279034.1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [90]:
# currPath=Path.cwd()
# normal_path = currPath.parents[1]/"Datasets/DESeq2Input/breastNormalCounts.csv"
# cancer_path = currPath.parents[1]/"Datasets/DESeq2Input/breastCancerCounts.csv"
# output_folder_normal = currPath.parents[1]/"Datasets/DESeq2Input/BreastNormalSingle/"
# output_folder_cancer = currPath.parents[1]/"Datasets/DESeq2Input/BreastCancerSingle/"

In [110]:
currPath=Path.cwd()
normal_path = currPath.parents[1]/"Datasets/DESeq2Input/lungNormalCounts.csv"
cancer_path = currPath.parents[1]/"Datasets/DESeq2Input/lungCancerCounts.csv"
output_folder_normal = currPath.parents[1]/"Datasets/DESeq2Input/LungNormalSingle/"
output_folder_cancer = currPath.parents[1]/"Datasets/DESeq2Input/LungCancerSingle/"

In [111]:
# Read the CSV, assuming the first column has gene identifiers and 
# the rest of the columns are samples with counts.
df = pd.read_csv(cancer_path, index_col=0)

# For each sample (i.e., each column in df), export a separate CSV.
for sample_name in df.columns:
    # Extract just this sample’s counts, keeping the genes as rows.
    sample_df = df[[sample_name]]
    
    # Write out to a new CSV named after the sample
    output_file = f"{output_folder_cancer}/cancer_{sample_name}.csv"
    sample_df.to_csv(output_file)
    
    print(f"Saved: {output_file}")

Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_5faf8a12-a2aa-44f1-b099-02106766ec94.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_6855a406-c085-45c7-b789-981786f0c775.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_e2445ad6-2a6a-4ec3-84d8-93cc3c180a58.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_cded92df-9367-4ee5-930c-6c87bf2c8eb0.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_4b167e70-e4e6-47f7-9fe9-11cf20f0d442.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_29dd3ad7-f2c6-4abf-8e81-6734e4bd8a6a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_51c0568a-3e54-42a0-b805-0a90905cc865.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_470afda8-c4a4-4161-b6e7-1f0d2372d2c7.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_a4b8b2f2-6a56-4999-bd95-c2c8e4aa3bd0.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_51054c11-8e2f-4f52-bdaf-ebb515508a28.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_95abf543-3987-4436-ba2a-a15e9c244d77.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_bf456ccc-e7bb-40e0-9e92-03e6ced8564b.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_8a884668-03c2-44bb-8ea0-5b0d0bc68aa4.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_cab5b00a-9cf2-4e1f-b2f3-93d27b73631e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_b9719e93-b44f-4eb3-8fe9-14914e643d57.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_4ca257ea-95ef-4881-8ab5-cd3ee88dbb6d.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_3b850000-76d1-4070-8bed-52add20750d0.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_26ea6a31-ea33-4bb9-814f-c0840dafe69e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_7aec753d-4fad-42f3-a5f8-066ed421d069.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_b770f87e-a9a9-4748-8649-86baf9629dad.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_e4d47a4b-0dd3-471f-86e7-7c682d646e98.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_d54e9279-578f-40cd-8e55-fbd7af5279dd.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_911a72ec-dcb3-4454-8f22-7bd4f9d29b21.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_661b6fed-d56a-452b-adaa-4b48ee9f4dbb.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_c2cdff0a-7852-47e3-b222-c51289e9d305.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_2a7831f2-aa57-4e6f-92b3-0a7a727d5637.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_9248b749-a2ae-4d64-a0b4-3c2bf0f7ed62.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_4fc4b4e0-6a01-4e8f-89f8-f68203f0105d.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_cfac28bf-001d-4db8-942a-d244f93139a7.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_f7a10e9e-496d-4664-b62d-c2d5e6ea662c.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_84f2b69e-86e5-4bf6-a11c-289b1971775f.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_1d7b2b60-11d7-4803-8c7f-45fc6ce45a25.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_dedf9f52-7ded-4cc5-bba2-da89a48b5176.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_f47927c5-e1e9-4152-9817-79aa6e64111a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_92b4ef29-b45a-4ec4-9251-8d6fb32cde90.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_3e752bb7-c91d-46f8-ba39-a40e26357b4d.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_ffec28dd-cc44-4057-bcc3-ccc0cd2331c2.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_41f4ae8d-e832-46e4-aa65-87ba050d39d3.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_505bfb1f-dc96-4f7e-ba2c-8e20eb0e1f6c.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_7da3a15e-9911-4429-98e7-d7ee03d7ad7f.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_5bb8ce26-770f-48cc-a481-466469d34073.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_968c4aa2-2bcd-4823-b7fa-fbedc41ddb25.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_74762046-1558-44bd-aa87-57dddc47c749.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_ba3e1d1e-3193-4770-9c57-b4ff1502af38.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_6d0c282d-43d7-44fb-94e6-25771385e326.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_1a06f92b-21c5-4666-b666-8b9135a4482a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_4a5c811e-d5d9-48d7-9bcc-4c9dc72df8f4.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_1529d8e6-10d2-4e7c-bfb1-66820434c835.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_90b9c230-9813-4c8e-b9e7-9018ccd21d28.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_858abd7d-396c-4dd3-b570-94f99ac9b9c0.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_42afded2-aa23-4f7f-b86f-ac47b324db1d.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_269a7c8d-f4d6-4f1a-a85b-874934f214b9.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_000b6b94-572d-4d06-a8f4-2e43829f83d4.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_6525f4e0-ba79-4576-89b3-df0ab6e45309.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_edc9bf50-9542-433d-af38-283b4e77f17b.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_3d6cb261-d0c4-4e98-8918-d7d678cb97ae.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_477d7181-e081-4577-ac06-e508b1239989.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_404d7866-9cac-48fa-86e4-7215cad5cf27.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_caa4bc15-6e54-4d5e-9d91-c25e800b71b9.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_ac55bde0-199a-410d-8127-e2ac2a320e2b.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_94913b2f-256e-4487-90ed-2c9b3869ca6b.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_bbbd3cd5-cfd3-418b-ab3a-243de430a5e1.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_e6543906-a4e3-447c-8040-310979304204.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_320660cd-100a-4f5a-a604-4de3ced7f042.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_5ecec8fc-845f-43cf-82c3-73dea85cc53c.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_f8670621-43a9-491c-81b7-8999ca9975a7.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_0052ae83-7ae5-470a-a125-5cd94a9fa9e9.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_6b3887e7-fbf3-402a-bd2d-895ad964dfbe.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_44d8e988-1a2b-4588-a64a-cf5a6c164e03.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_d64e9bd5-868a-4c9b-89a2-5510f4319c75.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_fe20855f-d3ce-4e02-b2dd-3df15eab44bf.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_0765d9e8-0fec-46bc-832a-89945435d5b1.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_87b1a89f-591c-4d6b-929d-2eae2951740e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_d5a9ed78-88ed-409c-8947-f1cd3fa6fce9.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_e4864765-ea64-404a-8892-2bbe22684521.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_10bec46a-08c3-4fe7-a65a-d801705fca17.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_26c96b62-02b6-4108-9a2d-bec3d880db2a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_0b050c63-6aed-4573-bac1-30d36781fb1a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_8be349eb-2407-4f51-809a-ceb5542e0cf1.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_55831884-c907-457d-bb2c-7c7b3f7c4cd1.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_45d4b468-9089-46fd-8b5e-ad80a5148abd.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_021326fa-7b6c-45c0-b078-4646c2260068.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_3cbe42eb-653f-4d85-aa94-e803a1f3516b.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_3ceaa569-c317-4e2f-a8e5-77db311e6032.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_a51aca71-6bfd-4c02-86e2-cb8a1da7595d.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_e79e25d8-4578-4e37-a740-91fba48ef40a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_2fa40914-d149-4f67-aa78-64723258314f.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_bbf261ac-5cb3-425e-b12a-b236aafde297.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_7fff3f50-1510-4cea-a335-29814fe0ab10.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_8d01df6d-4573-46dd-8f59-2b7b9aba7269.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_f514f386-f7e8-4771-8d22-48430740328e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_2773ff80-83f6-4e19-a384-e2f0e7ae92b3.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_5ef157e9-bb3d-4214-a946-f5bc2bbf74b6.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_2ea24d12-dddd-4628-ab66-5c70805b07e2.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_afa5c7c4-02f8-4417-873c-378937f5fbbb.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_157223aa-aab5-4522-8ff2-8104ea3561d9.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_6c66987a-38f6-4125-8ac1-aa55921fcc26.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_723a8c8e-03e4-4f77-9944-f0c4a42ec3ce.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_0e480f18-0e72-444e-b7e1-956a439471ad.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_afdf58d1-5814-4e78-a92e-26fbcc97da32.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_b9839f31-8926-4fa3-9aae-bf15ee58e847.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_334cc9fa-3e9b-4462-b84d-dc595e89d537.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_22cae278-eb88-4685-9ff7-667e53b50a34.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_d84121c5-5421-43a4-825a-40f357ecc97b.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_3f474548-c7b2-4d5e-9f8d-03c800a094fe.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_f31f1008-cde3-4ca6-8864-8b1e7efbb856.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_f134bb5f-7ea6-4a38-85a9-150bb7c2eccc.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_3a0bf450-e1f0-44b3-81e0-fb4fdda6e54e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_7cf36ebf-b16e-49ac-bcc4-b127b1f2a3da.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_342ae6d9-d9b9-4458-8c39-19faf0c7aeac.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_1098101e-1770-4055-ae41-d6c15e1c7b90.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_44959554-954a-43aa-aa22-1b2db64a790f.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_441e6227-4fa3-4891-92ec-8a6f93a02ec6.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_63853c66-8004-4205-8c0c-9b92d02f7ea1.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungCancerSingle/cancer_669ce970-42a3-4797-bf9c-0de40a021bbf.csv

In [112]:
# Read the CSV, assuming the first column has gene identifiers and 
# the rest of the columns are samples with counts.
df = pd.read_csv(normal_path, index_col=0)

# For each sample (i.e., each column in df), export a separate CSV.
for sample_name in df.columns:
    # Extract just this sample’s counts, keeping the genes as rows.
    sample_df = df[[sample_name]]
    
    # Write out to a new CSV named after the sample
    output_file = f"{output_folder_normal}/normal_{sample_name}.csv"
    sample_df.to_csv(output_file)
    
    print(f"Saved: {output_file}")

Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_29dd3ad7-f2c6-4abf-8e81-6734e4bd8a6a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_a4b8b2f2-6a56-4999-bd95-c2c8e4aa3bd0.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_661b6fed-d56a-452b-adaa-4b48ee9f4dbb.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_1a06f92b-21c5-4666-b666-8b9135a4482a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_94913b2f-256e-4487-90ed-2c9b3869ca6b.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_55831884-c907-457d-bb2c-7c7b3f7c4cd1.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_3ceaa569-c317-4e2f-a8e5-77db311e6032.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_bbf261ac-5cb3-425e-b12a-b236aafde297.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_3f474548-c7b2-4d5e-9f8d-03c800a094fe.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_63853c66-8004-4205-8c0c-9b92d02f7ea1.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_8dbb93bd-bf45-4148-acdb-6609d5c4a1e3.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_a4377fa6-f7e2-4289-ac2d-3cc87b6cc289.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_b77287b2-6fef-4978-a682-ccf09f1e781a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_75473987-65e2-43eb-a5bb-04cb7a40c902.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_bb64143e-c48a-45c7-914b-4ec5bcea9e27.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_bbd90b7b-3f75-463a-8ae6-1896cfa6e7d7.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_cc8fe981-25f1-4b07-a931-7ad2a352d2d8.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_e39f6bf6-2206-45f2-a1c0-81fc1d858fd2.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_7ccc40b9-a636-407f-928b-1522061f5acf.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_ad62355a-f287-49b2-84a9-64c0f5847c20.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_359d07bf-89e3-49fd-8237-723ffb299cfb.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_3f441cc8-98bd-4650-b5ad-19ae8542b666.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_23a2176b-1fa3-4360-ab55-5683b4de2184.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_dc782ae2-13ec-4fcd-bae7-cafa8280d5ee.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_5d65e761-0cb3-4e52-b14f-79be5850dba4.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_b43ead60-cb91-489a-88f1-169086a28ed9.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_e4988cad-67b9-41a6-9640-2226d6b7424a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_a8252e2f-1dbd-4f3c-9e11-599a33d6fd24.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_736d8419-1f66-49d6-83c7-e37b2fbff267.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_5a37129a-9672-4fda-8576-e7de1db7b2c2.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_b502b174-162a-49ea-ac55-5ec9a15aeaa6.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_7ffac92b-a35c-4283-882c-806a2e28a963.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_f36f6f42-60d3-49ea-8397-5a9663c54671.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_e6e83fd4-2f80-44e1-8dce-588a37308dbb.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_0d1f21df-73b3-4dd0-9ad4-fd5c7a5d2424.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_6359ce06-e708-45bb-9305-6780635d17be.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_e1a4e922-876b-45d1-8fb6-5d39dbf6ff60.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_132e38da-ca1b-4fc5-a462-f1eab6fd2e6e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_46211d46-b4da-43ed-8b36-abbed4f4f27e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_3ce6800e-9df0-45a7-9e18-7e141911e4e9.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_14e565dd-f3cd-4d99-9d11-d7b9b5165ea1.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_d4778869-f3f2-481b-ab02-65a654128766.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_aab3583f-37ca-4f2f-8428-aa8eda2c2274.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_54a00dd0-503f-471f-88e4-8d6fcdcf8483.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_2fe6f165-3396-4abd-a0cd-07968d826828.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_bfd852d9-9d72-4a3b-8ef3-e1435ef376fb.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_b6d704be-2e8f-40cc-9c09-ffde6be5c814.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_915f5f6d-b66b-4ffd-a095-a6bb60387d2f.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_efb3bf8d-7d14-42d6-8845-e81af909d47f.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_6b95a5c7-0b98-4f90-a8b2-22490d2cc0ce.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_c67f194f-0c71-4835-801c-5b6da7a583ef.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_df86c451-62c7-43bc-9b11-463181a5a98a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_2ee0c587-0e64-4d06-8e16-5dc009175c54.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_ca8dc4e0-e8d2-4574-b3a0-74b058bd2b96.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_ef229777-5389-4bc3-a2cd-f885d7b5f3b8.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_c48eecc3-0099-4dd4-b319-f13ad65bdc7e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_56e9a740-ee72-4c10-a90d-921034141b42.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_f8cee5c6-bfd7-439d-8ba7-20ee2dfa5d68.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_17d01bba-1ae8-4205-ae80-2db88489fa84.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_f822b8ac-5682-4ae1-8250-9f204fa540ea.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_28e41191-6834-4284-b960-d898ad7b3a99.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_550ec5d4-6618-4882-a783-be48163b6c30.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_81152340-ffac-4122-8b21-bef3a474a18e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_7671d2c4-d6da-46d5-8ef0-baab496456d2.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_f700b996-2ccf-4f59-9249-da7f087054ba.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_afcab3fd-65b3-463a-86c7-ca84d580db00.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_a71c722c-3483-4910-926d-c79b6c9a4e7d.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_fc8ef0dc-9a48-4eba-aeb6-9eec106739ca.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_d6612221-f6c7-4adb-8402-7df979b35e03.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_a6298ad5-dd68-44f6-85cf-f1d2c7673aa3.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_9c7f6057-8225-4447-adb3-aed12aa974ad.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_0cd79b1c-d9c2-4aee-8976-7174cdececae.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_53b14fb6-9f29-412a-921b-49e270fa2039.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_ce53fd27-c9f6-4e0f-87ad-4a596e5a2cd8.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_bdd8f5e2-1b65-4c8d-8527-88b892cbb8fe.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_bbb426a9-806b-4417-a3cd-4dd1b0c87792.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_98aaf3db-54ac-4bb9-bd0b-1ba897f7b389.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_2d99f93c-797e-49a5-8892-a4e31e17b9c3.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_09fb135f-1c19-45d6-ae31-a8c32a0e06bf.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_136ceaee-2156-4f8a-9fb8-250018e9498d.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_a5c19494-731c-4519-b8a7-b7307aea2f9c.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_e6fbcebb-6fe9-4b0e-aa82-cf42e72b8785.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_d9431251-cfae-44c2-a428-d80b96d58742.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_24079217-3899-4843-81fc-638293771d93.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_4fa865be-49fe-48f8-9e87-e09168572af4.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_bd98b566-f179-4be8-8b4d-672149eedcba.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_eac45bfd-6795-47a4-8d6b-5a7c8bc76cd1.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_52a4b995-1a94-4d89-9ff5-ca22b658c6d4.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_944adc4b-049d-4bce-90a0-d1b18a2d1e5e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_4756b201-87c2-4428-b2cd-f933422fe8cf.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_868f6883-6e7b-4565-ae15-813e282d8635.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_2ff24c33-39c6-4171-af42-f54e4ee8b021.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_bdae198f-aedf-46cc-8156-c1ec37eac88f.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_d532537c-a2dd-41c1-ac55-1eb15ac1245e.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_ecfc7942-e9ba-44ca-a219-9ba06b28b570.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_9f01664c-19be-4841-afb4-297483d22ec8.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_f47f1b37-e4a3-4f87-97c5-251ec084cdd9.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_4a5f6af0-e0d1-4657-9bdc-85eb6c31ffbb.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_420632d5-48e3-45f1-8480-3ec4d381ea55.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_c5922138-4e15-4546-b8a2-8cec6917262d.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_89bdfb20-8991-4bc4-b112-6e9be096b566.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_d29660d3-b3f7-4186-8c71-bebbabee600a.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_46ef57a2-e2ce-4ffe-9ce8-c043c6065863.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_9ad544f6-b684-4a97-8d05-f812267962bb.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_6c20a899-c806-46d0-b744-a26e53a9cb45.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_be7b80c8-2256-4725-a330-7435742aa309.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_c36f84e5-8c59-46fe-af32-7f70684383b2.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_4c994cf9-52d0-4c05-97c0-fd2d3ffb9100.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_94613d97-0a68-4212-beef-3c97a0b363ef.csv
Saved: /Users/simransodhi/Desktop/CMU/Spring 2025/Bioinformatics (02-604)/Project/Code/Datasets/DESeq2Input/LungNormalSingle/normal_d1f98c65-fd27-4893-a5c5-bc0bfe16ac5f.csv